/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jugador;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kendall-sanabria
 */
public class Configuracion extends javax.swing.JFrame {
    private ArrayList<Luchador> luchadores = new ArrayList<Luchador>();
    private String nombre;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Configuracion.class.getName());

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        cargarHabilidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnPredeterminados = new javax.swing.JButton();
        txfNombreC = new javax.swing.JTextField();
        txfLuchador = new javax.swing.JTextField();
        btnCivilizacion = new javax.swing.JButton();
        lblNombreC = new javax.swing.JLabel();
        lblLuchador = new javax.swing.JLabel();
        lblHabilidad = new javax.swing.JLabel();
        boxHabilidad = new javax.swing.JComboBox<>();
        lblPoder = new javax.swing.JLabel();
        spnPoder = new javax.swing.JSpinner();
        lblResistencia = new javax.swing.JLabel();
        lblSanidad = new javax.swing.JLabel();
        spnResistencia = new javax.swing.JSpinner();
        spnSanidad = new javax.swing.JSpinner();
        lblRepresentacion = new javax.swing.JLabel();
        txfRepresentacion = new javax.swing.JTextField();
        btnAgregarLuchador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(0, 102, 102));

        btnJugar.setFont(new java.awt.Font("Ubuntu Sans Mono", 0, 24)); // NOI18N
        btnJugar.setText("Jugar");

        btnPredeterminados.setFont(new java.awt.Font("URW Bookman", 0, 18)); // NOI18N
        btnPredeterminados.setText("Usar configuración predeterminada");

        btnCivilizacion.setText("Crear civilización");
        btnCivilizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCivilizacionActionPerformed(evt);
            }
        });

        lblNombreC.setText("Nombre de civilización");

        lblLuchador.setText("Nombre Luchador");

        lblHabilidad.setText("Habilidad");

        DefaultComboBoxModel<Habilidad> modelo = new DefaultComboBoxModel<>();
        modelo.addElement(new ThunderUnderTheSea("Thunder Under The Sea")); 
        modelo.addElement(new FishTelepathy("Fish Telepathy"));
        modelo.addElement(new ReleaseKraken("Release The Kraken"));
        modelo.addElement(new WavesControl("Waves Control"));
        modelo.addElement(new Trident("The Trident"));
        modelo.addElement(new UnderseaVolcanoes("Undersea Volcanoes"));

        boxHabilidad.setModel(modelo);
        boxHabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxHabilidadActionPerformed(evt);
            }
        });

        lblPoder.setText("Poder");

        spnPoder.setModel(new javax.swing.SpinnerNumberModel(50, 50, 100, 25));

        lblResistencia.setText("Resistencia");

        lblSanidad.setText("Sanidad");

        spnResistencia.setModel(new javax.swing.SpinnerNumberModel(100, 50, 100, 25));

        spnSanidad.setModel(new javax.swing.SpinnerNumberModel(75, 50, 100, 25));

        lblRepresentacion.setText("Representación");

        btnAgregarLuchador.setText("Agregar Luchador");
        btnAgregarLuchador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLuchadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPoder, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblSanidad))
                            .addComponent(lblLuchador)
                            .addComponent(lblRepresentacion))
                        .addGap(32, 32, 32)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlFondoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblResistencia, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNombreC, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnAgregarLuchador, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(pnlFondoLayout.createSequentialGroup()
                                        .addComponent(txfLuchador, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblHabilidad)))
                                .addGap(46, 46, 46)
                                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boxHabilidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spnResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfNombreC))
                                .addGap(126, 126, 126))
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnSanidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfRepresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(555, Short.MAX_VALUE))))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(btnCivilizacion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPredeterminados)
                        .addGap(55, 55, 55))))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCivilizacion)
                    .addComponent(txfNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreC))
                .addGap(56, 56, 56)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfLuchador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLuchador)
                    .addComponent(lblHabilidad)
                    .addComponent(boxHabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResistencia)
                    .addComponent(spnResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoder))
                .addGap(18, 18, 18)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSanidad)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(spnSanidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfRepresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRepresentacion))))
                .addGap(32, 32, 32)
                .addComponent(btnAgregarLuchador)
                .addGap(28, 28, 28)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPredeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCivilizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCivilizacionActionPerformed
        if (luchadores.size() !=  3){
            JOptionPane.showMessageDialog(null, "Te faltan mas luchadores, apenas llevas: " + luchadores.size());
        } else {
            String nombreCivilizacion =txfNombreC.getText();
            Civilizacion civilizacion = new Civilizacion(nombreCivilizacion, luchadores.get(0), luchadores.get(1), luchadores.get(2));
            
            System.out.println("Civilizacion agregada correctamente");
        }
        
        
    }//GEN-LAST:event_btnCivilizacionActionPerformed

    private void boxHabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxHabilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxHabilidadActionPerformed

    private void btnAgregarLuchadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLuchadorActionPerformed
        if (luchadores.size() < 3){
            String nombreLuchador = txfLuchador.getText();
            String nombreCivilizacion =txfNombreC.getText();
            Habilidad habilidadSeleccionada = (Habilidad) boxHabilidad.getSelectedItem();
            int poder = (int)spnPoder.getValue();
            int sanidad = (int)spnSanidad.getValue();
            int resistencia = (int)spnResistencia.getValue();
            int representacion = 0;
            //TODO: obtener la direccion de imagen y agregarla al instanciar luchador

            try {
                representacion = Integer.parseInt(txfRepresentacion.getText());
                
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Por favor ingresa un número válido");
            }
            luchadores.add(new Luchador(nombreCivilizacion, nombreLuchador, habilidadSeleccionada, representacion, poder, sanidad, resistencia));
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Ya llevas 3 luchadores, en esta civilizacion no puedes meter mas");
        }
    }//GEN-LAST:event_btnAgregarLuchadorActionPerformed
    
    private void cargarHabilidades() {
        DefaultComboBoxModel<Habilidad> modelo = new DefaultComboBoxModel<>();
        modelo.addElement(new ThunderUnderTheSea("Thunder Under The Sea")); 
        modelo.addElement(new FishTelepathy("Fish Telepathy"));
        modelo.addElement(new ReleaseKraken("Release The Kraken"));
        modelo.addElement(new WavesControl("Waves Control"));
        modelo.addElement(new Trident("The Trident"));
        modelo.addElement(new UnderseaVolcanoes("Undersea Volcanoes"));

        boxHabilidad.setModel(modelo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Configuracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Habilidad> boxHabilidad;
    private javax.swing.JButton btnAgregarLuchador;
    private javax.swing.JButton btnCivilizacion;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPredeterminados;
    private javax.swing.JLabel lblHabilidad;
    private javax.swing.JLabel lblLuchador;
    private javax.swing.JLabel lblNombreC;
    private javax.swing.JLabel lblPoder;
    private javax.swing.JLabel lblRepresentacion;
    private javax.swing.JLabel lblResistencia;
    private javax.swing.JLabel lblSanidad;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JSpinner spnPoder;
    private javax.swing.JSpinner spnResistencia;
    private javax.swing.JSpinner spnSanidad;
    private javax.swing.JTextField txfLuchador;
    private javax.swing.JTextField txfNombreC;
    private javax.swing.JTextField txfRepresentacion;
    // End of variables declaration//GEN-END:variables
}
