/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jugador;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;

/**
 *
 * @author kendall-sanabria
 */
public class Configuracion extends javax.swing.JFrame {
    private ArrayList<Luchador> luchadores = new ArrayList<Luchador>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Configuracion.class.getName());
    private String direccionImagen;
    private Client cliente;
    private Civilizacion civilizacion;
    private ArrayList<Integer> sanidadUsados = new ArrayList<>();
    private ArrayList<Integer> resistenciaUsados = new ArrayList<>();
    private ArrayList<Integer> poderUsados = new ArrayList<>();
    private int contadorRepresentacion = 0;
    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        setLocationRelativeTo(null);
        imagen();
        btnJugar.setEnabled(false);
        cargarSpn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnPredeterminados = new javax.swing.JButton();
        txfNombreC = new javax.swing.JTextField();
        txfLuchador = new javax.swing.JTextField();
        btnCivilizacion = new javax.swing.JButton();
        lblNombreC = new javax.swing.JLabel();
        lblLuchador = new javax.swing.JLabel();
        lblHabilidad = new javax.swing.JLabel();
        boxHabilidad = new javax.swing.JComboBox<>();
        lblPoder = new javax.swing.JLabel();
        spnPoder = new javax.swing.JSpinner();
        lblResistencia = new javax.swing.JLabel();
        lblSanidad = new javax.swing.JLabel();
        spnResistencia = new javax.swing.JSpinner();
        spnSanidad = new javax.swing.JSpinner();
        lblRepresentacion = new javax.swing.JLabel();
        btnAgregarLuchador = new javax.swing.JButton();
        spnRepresentacion = new javax.swing.JSpinner();
        btnCargarImagen = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(0, 102, 102));

        btnJugar.setFont(new java.awt.Font("Ubuntu Sans Mono", 0, 24)); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        btnPredeterminados.setFont(new java.awt.Font("URW Bookman", 0, 18)); // NOI18N
        btnPredeterminados.setText("Usar configuración predeterminada");
        btnPredeterminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPredeterminadosActionPerformed(evt);
            }
        });

        btnCivilizacion.setText("Crear civilización");
        btnCivilizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCivilizacionActionPerformed(evt);
            }
        });

        lblNombreC.setText("Nombre de civilización");

        lblLuchador.setText("Nombre Luchador");

        lblHabilidad.setText("Habilidad");

        boxHabilidad.setModel(new DefaultComboBoxModel<>(
            new Habilidad[] {
                new ThunderUnderTheSea(),
                new FishTelepathy(),
                new ReleaseKraken(),
                new WavesControl(),
                new Trident(),
                new UnderseaVolcanoes()
            }));
            boxHabilidad.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    boxHabilidadActionPerformed(evt);
                }
            });

            lblPoder.setText("Poder");

            spnPoder.setModel(new javax.swing.SpinnerListModel(new String[] {"50", "75", "100"}));

            lblResistencia.setText("Resistencia");

            lblSanidad.setText("Sanidad");

            spnResistencia.setModel(new javax.swing.SpinnerListModel(new String[] {"50", "75", "100"}));

            spnSanidad.setModel(new javax.swing.SpinnerListModel(new String[] {"50", "75", "100"}));

            lblRepresentacion.setText("Representación");

            btnAgregarLuchador.setText("Agregar Luchador");
            btnAgregarLuchador.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAgregarLuchadorActionPerformed(evt);
                }
            });

            spnRepresentacion.setModel(new javax.swing.SpinnerNumberModel(20, 10, 100, 10));

            btnCargarImagen.setText("Cargar imagen");

            lblImagen.setText(".");

            javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
            pnlFondo.setLayout(pnlFondoLayout);
            pnlFondoLayout.setHorizontalGroup(
                pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFondoLayout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlFondoLayout.createSequentialGroup()
                            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPoder, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblSanidad))
                                    .addComponent(lblLuchador)
                                    .addComponent(lblResistencia))
                                .addGroup(pnlFondoLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(btnCargarImagen)))
                            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlFondoLayout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlFondoLayout.createSequentialGroup()
                                            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(pnlFondoLayout.createSequentialGroup()
                                                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlFondoLayout.createSequentialGroup()
                                                            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(pnlFondoLayout.createSequentialGroup()
                                                                    .addComponent(txfLuchador, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                                                                    .addComponent(lblHabilidad))
                                                                .addGroup(pnlFondoLayout.createSequentialGroup()
                                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                                    .addComponent(lblNombreC)))
                                                            .addGap(46, 46, 46))
                                                        .addGroup(pnlFondoLayout.createSequentialGroup()
                                                            .addComponent(spnResistencia)
                                                            .addGap(424, 424, 424)))
                                                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(boxHabilidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(txfNombreC))
                                                        .addComponent(lblImagen)))
                                                .addGroup(pnlFondoLayout.createSequentialGroup()
                                                    .addGap(370, 370, 370)
                                                    .addComponent(lblRepresentacion)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(spnRepresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(126, 126, 126))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFondoLayout.createSequentialGroup()
                                            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(spnPoder, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                .addComponent(spnSanidad))
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(pnlFondoLayout.createSequentialGroup()
                                    .addGap(319, 319, 319)
                                    .addComponent(btnAgregarLuchador)
                                    .addContainerGap())))
                        .addGroup(pnlFondoLayout.createSequentialGroup()
                            .addComponent(btnCivilizacion)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(pnlFondoLayout.createSequentialGroup()
                            .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPredeterminados)
                            .addGap(55, 55, 55))))
            );
            pnlFondoLayout.setVerticalGroup(
                pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFondoLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCivilizacion)
                        .addComponent(txfNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreC))
                    .addGap(56, 56, 56)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfLuchador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLuchador)
                        .addComponent(lblHabilidad)
                        .addComponent(boxHabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPoder))
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnRepresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRepresentacion)))
                    .addGap(24, 24, 24)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSanidad)
                        .addGroup(pnlFondoLayout.createSequentialGroup()
                            .addComponent(spnSanidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblImagen)
                                .addComponent(lblResistencia)
                                .addComponent(spnResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(37, 37, 37)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCargarImagen)
                        .addComponent(btnAgregarLuchador))
                    .addGap(50, 50, 50)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPredeterminados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(82, 82, 82))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnCivilizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCivilizacionActionPerformed
        if (luchadores.size() !=  3){
            JOptionPane.showMessageDialog(null, "Te faltan mas luchadores, apenas llevas: " + luchadores.size());
        } else if (this.contadorRepresentacion > 100 || this.contadorRepresentacion < 100) {
            JOptionPane.showMessageDialog(null, "Error, la representacion esta incorrecta: " + this.contadorRepresentacion + " Por favor hazlos de nuevo");
            luchadores.clear();
            txfNombreC.setText("");
            contadorRepresentacion = 0;
            this.direccionImagen = "";
            sanidadUsados.clear();
            resistenciaUsados.clear();
            poderUsados.clear();
            cargarSpn();
        } else {
            String nombreCivilizacion =txfNombreC.getText();
            this.civilizacion = new Civilizacion(nombreCivilizacion, luchadores.get(0), luchadores.get(1), luchadores.get(2));
            civilizacion.setLuchadores(luchadores);
            cliente = new Client(civilizacion);
            btnJugar.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_btnCivilizacionActionPerformed

    private void boxHabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxHabilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxHabilidadActionPerformed

    private void btnAgregarLuchadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLuchadorActionPerformed
        if (luchadores.size() < 3){
            if (txfLuchador.getText().isEmpty() || txfNombreC.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Por favor ingresa un nombre");
                
            } else if (direccionImagen.isEmpty()|| direccionImagen == null){
                JOptionPane.showMessageDialog(null, "Por favor carga una imagen");
                
            } else {                
                String nombreLuchador = txfLuchador.getText();
                String nombreCivilizacion =txfNombreC.getText();
                Habilidad habilidadSeleccionada = (Habilidad) boxHabilidad.getSelectedItem();
                
                int poder = Integer.parseInt(spnPoder.getValue().toString());
                int sanidad = Integer.parseInt(spnSanidad.getValue().toString());
                int resistencia = Integer.parseInt(spnResistencia.getValue().toString());
                if (sanidadUsados.size() != 1) {
                    eliminarElemento(poderUsados, poder);
                    SpinnerListModel modelP = new SpinnerListModel(poderUsados);
                    spnPoder.setModel(modelP);


                    System.out.println("" + sanidad);
                    eliminarElemento(sanidadUsados, sanidad);
                    SpinnerListModel modelS = new SpinnerListModel(sanidadUsados);
                    spnSanidad.setModel(modelS);


                    System.out.println("" + resistencia);
                    eliminarElemento(resistenciaUsados, resistencia);
                    SpinnerListModel modelR = new SpinnerListModel(resistenciaUsados);
                    spnResistencia.setModel(modelR);
                } 
                
                int representacion = (int)spnRepresentacion.getValue();
                    this.contadorRepresentacion += representacion;
                
                if (contadorRepresentacion > 100) {
                    JOptionPane.showMessageDialog(null, "La representacion de los luchadores no esta correcta! Por favor crealos de nuevo");
                    luchadores.clear();
                    txfNombreC.setText("");
                    contadorRepresentacion = 0;
                    this.direccionImagen = "";
                    sanidadUsados.clear();
                    resistenciaUsados.clear();
                    poderUsados.clear();
                    cargarSpn();
                    return;
                }
                luchadores.add(new Luchador(nombreCivilizacion, 
                        nombreLuchador, habilidadSeleccionada, 
                        representacion, poder, sanidad, 
                        resistencia, direccionImagen));
                this.direccionImagen = "";
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ya llevas 3 luchadores, en esta civilizacion no puedes meter mas\n");
        }
    }//GEN-LAST:event_btnAgregarLuchadorActionPerformed

    private void eliminarElemento(ArrayList<Integer> lista, int elemento) {
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i) == elemento) {
                lista.remove(i);
            }
        }
    }
    private void btnPredeterminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPredeterminadosActionPerformed
        //cargar luchadores y civilizacion mas rapido
        //String civilizacion, String nombre, Habilidad habilidad, int representacion, int poder, int sanidad, int resistencia, String direccionImagen

        Luchador luchador1 = new Luchador("Ateneida","Zeus", new ReleaseKraken(), 50, 100, 75, 50, getClass().getResource("/images/zeus.png").getPath());
        Luchador luchador2 = new Luchador("Ateneida","Poseidon", new Trident(), 20, 50, 100, 50, getClass().getResource("/images/poseidon.png").getPath());
        Luchador luchador3 = new Luchador("Ateneida","Kratos", new UnderseaVolcanoes(), 30, 75, 100, 75, getClass().getResource("/images/kratos.png").getPath());
        luchadores.add(luchador1);
        luchadores.add(luchador2);
        luchadores.add(luchador3);
        
        this.civilizacion = new Civilizacion("Ateneida", luchador1, luchador2, luchador3);
        civilizacion.setLuchadores(luchadores);
        cliente = new Client(civilizacion);
        cliente.connect();
        dispose();
    }//GEN-LAST:event_btnPredeterminadosActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        cliente.connect();
        dispose();
    }//GEN-LAST:event_btnJugarActionPerformed


    private void imagen(){
        btnCargarImagen.addActionListener(e -> {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar imagen");

        // Filtro para solo imágenes
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Imágenes (JPG, PNG, GIF)", "jpg", "jpeg", "png", "gif"
        ));

        int resultado = fileChooser.showOpenDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();

            // 🔹 Mostrar la imagen en un JLabel, por ejemplo:
            ImageIcon icono = new ImageIcon(archivoSeleccionado.getAbsolutePath());

            // Escalar la imagen para que no se vea gigante
            Image imagenEscalada = icono.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            lblImagen.setIcon(new ImageIcon(imagenEscalada)); 
            this.direccionImagen = archivoSeleccionado.getAbsolutePath();
        }
        
        });
    }
    
    
    private void cargarSpn() {
        sanidadUsados.add(50);
        sanidadUsados.add(75);
        sanidadUsados.add(100);
        
        poderUsados.add(50);
        poderUsados.add(75);
        poderUsados.add(100);
        
        resistenciaUsados.add(50);
        resistenciaUsados.add(75);
        resistenciaUsados.add(100);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Configuracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Habilidad> boxHabilidad;
    private javax.swing.JButton btnAgregarLuchador;
    private javax.swing.JButton btnCargarImagen;
    private javax.swing.JButton btnCivilizacion;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnPredeterminados;
    private javax.swing.JLabel lblHabilidad;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblLuchador;
    private javax.swing.JLabel lblNombreC;
    private javax.swing.JLabel lblPoder;
    private javax.swing.JLabel lblRepresentacion;
    private javax.swing.JLabel lblResistencia;
    private javax.swing.JLabel lblSanidad;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JSpinner spnPoder;
    private javax.swing.JSpinner spnRepresentacion;
    private javax.swing.JSpinner spnResistencia;
    private javax.swing.JSpinner spnSanidad;
    private javax.swing.JTextField txfLuchador;
    private javax.swing.JTextField txfNombreC;
    // End of variables declaration//GEN-END:variables
}
