/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thewalkingtec;

import java.util.ArrayList;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.awt.Color;
import java.io.*;
import java.util.*;




public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        lblError.setText("");
        setLocationRelativeTo(null);
        // Deshabilitar inicialmente
        btnEntrar.setEnabled(false);

        // Escuchar cambios en los dos campos
        javax.swing.event.DocumentListener listener = new javax.swing.event.DocumentListener() {
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { checkFields(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { checkFields(); }
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { checkFields(); }
        };

        txfUsuario.getDocument().addDocumentListener(listener);
        txfPswUsuario.getDocument().addDocumentListener(listener);
        
    }
    
    private void checkFields() {
        String usuario = txfUsuario.getText().trim();
        String password = txfPswUsuario.getText().trim();
        btnEntrar.setEnabled(!usuario.isEmpty() && !password.isEmpty());
    }

    
    private void agregarUsuario() {
        ArrayList<Usuario> usuarios = leerUsuarios();
        String usuario = txfUsuario.getText().trim();
        String password = txfPswUsuario.getText().trim();

        if (usuario.isEmpty() || password.isEmpty()) {
            lblError.setText("¡Por favor, digite su usuario y contraseña!");
            return;
        }


        boolean usuarioExiste = usuarios.stream()
                .anyMatch(u -> u.getUsuario().equalsIgnoreCase(usuario));

        if (usuarioExiste) {
            lblError.setText("Ese usuario ya existe.");
        } else {
            usuarios.add(new Usuario(usuario, password)); //  Agrega al ArrayList
            guardarUsuarios(usuarios);                    //  Lo guarda en JSON
            lblError.setText("Usuario agregado correctamente.");
            lblError.setForeground(Color.green);
        }
    }

    private ArrayList<Usuario> leerUsuarios() {
        File archivo = new File("usuarios.json");
        if (!archivo.exists()) {
            return new ArrayList<>();
        }

        try (Reader reader = new FileReader(archivo)) {
            Gson gson = new Gson();
            return gson.fromJson(reader, new TypeToken<List<Usuario>>(){}.getType());
        } catch (Exception e) {
            e.printStackTrace();
            return new ArrayList<>();
        }
    }
    
    private void guardarUsuarios(List<Usuario> usuarios) {
        try (Writer writer = new FileWriter("usuarios.json")) {
            Gson gson = new Gson();
            gson.toJson(usuarios, writer);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblPswUsuario = new javax.swing.JLabel();
        txfUsuario = new javax.swing.JTextField();
        txfPswUsuario = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDatosUsuario.setBackground(new java.awt.Color(204, 204, 204));

        lblUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblUsuario.setText("Nombre de usuario: ");

        lblPswUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblPswUsuario.setText("Contraseña:");

        btnAgregar.setText("Agregar usuario");
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setText("¡Por favor, digite su usuario y contraseña!");

        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntrar.setEnabled(false);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnJugar.setBackground(new java.awt.Color(255, 0, 0));
        btnJugar.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        btnJugar.setText("JUGAR");
        btnJugar.setToolTipText("");
        btnJugar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnJugar.setEnabled(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosUsuarioLayout = new javax.swing.GroupLayout(pnlDatosUsuario);
        pnlDatosUsuario.setLayout(pnlDatosUsuarioLayout);
        pnlDatosUsuarioLayout.setHorizontalGroup(
            pnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosUsuarioLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(pnlDatosUsuarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblError)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPswUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142))
                    .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfPswUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        pnlDatosUsuarioLayout.setVerticalGroup(
            pnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblPswUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfPswUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(pnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(lblError)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarUsuario();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        ArrayList<Usuario> usuarios = leerUsuarios();
        String usuario = txfUsuario.getText().trim();
        String password = txfPswUsuario.getText().trim();
        
        boolean credencialesValidas = usuarios.stream()
                .anyMatch(u -> u.getUsuario().equalsIgnoreCase(usuario)
                    && u.getPassword().equals(password));
        if (credencialesValidas) {            
            this.setVisible(false);
            this.dispose(); // libera recursos del JFrame
            
        } else {
            lblError.setText("Usario o contraseña incorrectos");
        }        
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        //TODO: juega con una configuracion por default
        
        this.setVisible(false);
        this.dispose(); // libera recursos del JFrame
    }//GEN-LAST:event_btnJugarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPswUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlDatosUsuario;
    private javax.swing.JTextField txfPswUsuario;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables
}
