/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.walkingtec;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author josed
 */
public class Celda extends javax.swing.JPanel {

    private boolean ocupada;
    
    public Celda() {
        initComponents();
        this.ocupada = false;
        setLayout(new BorderLayout());
        setBackground(Color.GREEN);
        setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
    }

    public boolean estaOcupada() {
        return ocupada;
    }
    
    public void ocupar(){
        this.ocupada = true;
        setBackground(Color.RED);
    }
    
    public void liberar(){
        this.ocupada = false;
        setBackground(Color.GREEN);
    }
    
    public void setColorEstructura(){
        removeAll();
        setBackground(new Color(230,220,150));
        ocupada = true;
        revalidate();
        repaint();
    }
    
    public void setImgEstructura(JLabel estructura){
        removeAll();
        setBackground(new Color(230,220,150));
        ocupada = true;        
        add(estructura, BorderLayout.CENTER); // agrega centrado
        revalidate();
        repaint();
    }
    
    
    public void agregarEntidad(JLabel entidad){
        removeAll();
        ocupada = true;
        add(entidad);
        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
