/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.walkingtec;


import java.awt.*;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author josed
 */
public class PantallaJuego extends javax.swing.JFrame {
    private Reliquia reliquia;
    private CampoBatalla campo;
    private int nivel;
    
    public PantallaJuego(int nivelActual) {
        initComponents();
        this.nivel = nivelActual;
        inicializar();
    }
     
    private void inicializar() {
        setLayout(new BorderLayout());
        
        CampoBatalla campo = new CampoBatalla(this);
        setContentPane(campo);
        this.campo = campo;
        pack();
        setLocationRelativeTo(null);

        //while {  condiciones para que el mae reinicie o avance, continua
        campo.jugar(nivel);
        nivel++;
        
        //}
    }
    
    public void guardarPartida(){
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Guardar partida como...");
        int opcion = chooser.showSaveDialog(this);
        
        if (opcion == JFileChooser.APPROVE_OPTION){
            File archivo = chooser.getSelectedFile();
            try (ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream(archivo))){
                output.writeObject(new Partida(nivel));
                JOptionPane.showMessageDialog(this, "Partida guardada correctamente.");
            } catch (IOException e){
                JOptionPane.showMessageDialog(this, "Error al guardar la partida.");
            }
        }
    }
    
    public void avanzarNivel(){
        nivel++;
        guardarPartida();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}