/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.walkingtec;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author josed
 */
public class Pantalla extends javax.swing.JFrame {
    public static final int SCALE_DEFAULT = 80;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());
    private ImageIcon image;
    private ImageIcon icon;
    int ancho = 100;
    int alto = 100;
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        JFrame frame = new JFrame("JLabel con Imagen");
        frame.setSize(400, 300);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLayout(null);

        // Cargar imagen
        ImageIcon icon = new ImageIcon("/imagenes/Calavera.png");

        // Crear JLabel con imagen
        JLabel label = new JLabel(icon);
        label.setBounds(50, 50, icon.getIconWidth(), icon.getIconHeight());

        // Agregar al frame
        frame.add(label);
        frame.setVisible(true);
        initComponents();
        
        // Opcional: establecer tamaño preferido para el label
        lblEjemplo.setPreferredSize(new Dimension(150,150));

        // Insertar la imagen
        insertarImg(lblEjemplo, "D:\\PrograPOO\\TheWalkingTEC\\WalkingTEC\\imagenes\\Calavera.png");
    }
    private void insertarImg(JLabel lbl, String ruta) {
        // Cargar la imagen
        ImageIcon image = new ImageIcon(ruta);

        // Forzar la ejecución después de que el JLabel tenga tamaño válido
        SwingUtilities.invokeLater(() -> {
            // Tomar el tamaño real del JLabel
            int ancho = lbl.getWidth();
            int alto = lbl.getHeight();

            // Si el tamaño aún es 0, usar un valor por defecto
            if (ancho <= 0) ancho = 150;
            if (alto <= 0) alto = 150;

            // Escalar la imagen al tamaño del JLabel
            Image imgEscalada = image.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

            // Crear un nuevo ImageIcon con la imagen escalada
            ImageIcon icon = new ImageIcon(imgEscalada);

            // Asignar el icon al JLabel
            lbl.setIcon(icon);

            // Asegurarse de que la imagen se centre
            lbl.setHorizontalAlignment(JLabel.CENTER);
            lbl.setVerticalAlignment(JLabel.CENTER);

            // Borrar cualquier texto previo
            lbl.setText("");

            // Repaint para actualizar la vista
            lbl.repaint();
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFuerte = new javax.swing.JPanel();
        labelReliquia = new javax.swing.JLabel();
        lblEjemplo = new javax.swing.JLabel();
        panelControl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reliquiaUbicacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFuerte.setBackground(new java.awt.Color(204, 255, 204));
        panelFuerte.setPreferredSize(new java.awt.Dimension(25, 25));

        labelReliquia.setBackground(new java.awt.Color(102, 102, 255));
        labelReliquia.setOpaque(true);
        labelReliquia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelReliquiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelFuerteLayout = new javax.swing.GroupLayout(panelFuerte);
        panelFuerte.setLayout(panelFuerteLayout);
        panelFuerteLayout.setHorizontalGroup(
            panelFuerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuerteLayout.createSequentialGroup()
                .addGroup(panelFuerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFuerteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelReliquia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFuerteLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelFuerteLayout.setVerticalGroup(
            panelFuerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuerteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelReliquia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lblEjemplo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        panelControl.setBackground(new java.awt.Color(255, 153, 153));

        reliquiaUbicacion.setColumns(20);
        reliquiaUbicacion.setRows(5);
        jScrollPane1.setViewportView(reliquiaUbicacion);

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFuerte, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelFuerte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelReliquiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReliquiaMouseClicked
        int x = labelReliquia.getLocation().x;
        int y = labelReliquia.getLocation().y;
        reliquiaUbicacion.setText("Reliquia: "+x+", "+y);
    }//GEN-LAST:event_labelReliquiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pantalla().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelReliquia;
    private javax.swing.JLabel lblEjemplo;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelFuerte;
    private javax.swing.JTextArea reliquiaUbicacion;
    // End of variables declaration//GEN-END:variables
}
